package com.bytedance.sdk.openadsdk.component.view;

import android.content.Context;
import android.graphics.Color;
import android.text.TextUtils;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import com.bytedance.sdk.component.utils.cz;
import com.bytedance.sdk.openadsdk.core.customview.PAGFrameLayout;
import com.bytedance.sdk.openadsdk.core.customview.PAGImageView;
import com.bytedance.sdk.openadsdk.core.customview.PAGLinearLayout;
import com.bytedance.sdk.openadsdk.core.customview.PAGRelativeLayout;
import com.bytedance.sdk.openadsdk.core.customview.PAGTextView;
import com.bytedance.sdk.openadsdk.core.widget.PAGLogoView;
import com.bytedance.sdk.openadsdk.core.widget.TTRoundRectImageView;
import com.bytedance.sdk.openadsdk.utils.WNy;

/* loaded from: classes.dex */
public class PAGAppOpenOneLayout extends PAGAppOpenBaseLayout {
    public PAGAppOpenOneLayout(Context context) {
        super(context);
        setLayoutParams(new FrameLayout.LayoutParams(-1, -1));
        setBackgroundColor(Color.parseColor("#000000"));
        PAGLinearLayout pAGLinearLayout = new PAGLinearLayout(context);
        pAGLinearLayout.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        pAGLinearLayout.setOrientation(1);
        PAGRelativeLayout pAGRelativeLayout = new PAGRelativeLayout(context);
        pAGRelativeLayout.setId(520093753);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(-1, 0);
        layoutParams.weight = 84.0f;
        pAGRelativeLayout.setLayoutParams(layoutParams);
        PAGImageView pAGImageView = new PAGImageView(context);
        this.zp = pAGImageView;
        pAGImageView.setId(520093754);
        this.zp.setLayoutParams(new LinearLayout.LayoutParams(-1, -1));
        this.zp.setScaleType(ImageView.ScaleType.FIT_XY);
        PAGFrameLayout pAGFrameLayout = new PAGFrameLayout(context);
        this.lMd = pAGFrameLayout;
        pAGFrameLayout.setId(520093755);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-1, -1);
        layoutParams2.addRule(13);
        this.lMd.setLayoutParams(layoutParams2);
        PAGImageView pAGImageView2 = new PAGImageView(context);
        this.KS = pAGImageView2;
        pAGImageView2.setId(520093756);
        this.KS.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        PAGLogoView pAGLogoView = new PAGLogoView(context);
        this.jU = pAGLogoView;
        pAGLogoView.setId(520093757);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, WNy.lMd(context, 14.0f));
        layoutParams3.addRule(12);
        this.jU.setLayoutParams(layoutParams3);
        View zp = zp(context);
        pAGRelativeLayout.addView(this.zp);
        pAGRelativeLayout.addView(this.lMd);
        pAGRelativeLayout.addView(this.KS);
        pAGRelativeLayout.addView(this.jU);
        pAGRelativeLayout.addView(zp);
        pAGRelativeLayout.addView(this.YW);
        int lMd = WNy.lMd(context, 2.0f);
        int lMd2 = WNy.lMd(context, 20.0f);
        int lMd3 = WNy.lMd(context, 22.0f);
        int lMd4 = WNy.lMd(context, 40.0f);
        PAGLinearLayout pAGLinearLayout2 = new PAGLinearLayout(context);
        this.HWF = pAGLinearLayout2;
        pAGLinearLayout2.setId(520093758);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-1, 0);
        layoutParams4.weight = 16.0f;
        this.HWF.setLayoutParams(layoutParams4);
        this.HWF.setBackgroundColor(Color.parseColor("#FFFFFF"));
        this.HWF.setClickable(false);
        this.HWF.setGravity(17);
        this.HWF.setOrientation(0);
        this.HWF.setPadding(lMd2, 0, lMd2, 0);
        TTRoundRectImageView tTRoundRectImageView = new TTRoundRectImageView(context);
        this.QR = tTRoundRectImageView;
        tTRoundRectImageView.setId(520093759);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(lMd4, lMd4);
        layoutParams5.leftMargin = lMd;
        layoutParams5.rightMargin = lMd3;
        layoutParams5.setMarginStart(lMd);
        layoutParams5.setMarginEnd(lMd3);
        this.QR.setLayoutParams(layoutParams5);
        PAGTextView pAGTextView = new PAGTextView(context);
        this.ku = pAGTextView;
        pAGTextView.setId(520093761);
        this.ku.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        this.ku.setEllipsize(TextUtils.TruncateAt.END);
        this.ku.setMaxLines(2);
        this.ku.setTextColor(Color.parseColor("#161823"));
        this.ku.setTextSize(1, 22.0f);
        this.HWF.addView(this.QR);
        this.HWF.addView(this.ku);
        pAGLinearLayout.addView(pAGRelativeLayout);
        pAGLinearLayout.addView(this.HWF);
        addView(pAGLinearLayout);
    }

    public View zp(Context context) {
        ButtonFlash buttonFlash = new ButtonFlash(context);
        this.COT = buttonFlash;
        buttonFlash.setId(520093717);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(WNy.lMd(context, 180.0f), WNy.lMd(context, 43.0f));
        layoutParams.addRule(14);
        layoutParams.addRule(12);
        layoutParams.bottomMargin = WNy.lMd(context, 24.0f);
        this.COT.setLayoutParams(layoutParams);
        this.COT.setBackground(cz.KS(context, "tt_button_back"));
        this.COT.setEllipsize(TextUtils.TruncateAt.END);
        this.COT.setGravity(17);
        this.COT.setLines(1);
        this.COT.setText(cz.lMd(context, "tt_video_download_apk"));
        this.COT.setTextColor(Color.parseColor("#FFFFFF"));
        this.COT.setTextSize(1, 16.0f);
        this.COT.setTag("open_ad_click_button_tag");
        return this.COT;
    }
}
