package com.applovin.impl;

import com.applovin.impl.xj;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

/* loaded from: classes2.dex */
public abstract class ve extends sj {
    public static final sj A7;
    public static final sj B7;
    public static final sj C7;
    public static final sj D7;
    public static final sj E7;
    public static final sj F7;
    public static final sj G7;
    public static final sj H7;
    public static final sj I7;
    public static final sj J7;
    public static final sj K7;
    public static final sj L7;
    public static final sj M7;
    public static final sj N7;
    public static final sj O7;
    public static final sj P6 = sj.a("afi", "");
    public static final sj P7;
    public static final sj Q6;
    public static final sj Q7;
    public static final sj R6;
    public static final sj R7;
    public static final sj S6;
    public static final sj S7;
    public static final sj T6;
    public static final sj T7;
    public static final sj U6;
    public static final sj U7;
    public static final sj V6;
    public static final sj V7;
    public static final sj W6;
    public static final sj W7;
    public static final sj X6;
    public static final sj X7;
    public static final sj Y6;
    public static final sj Y7;
    public static final sj Z6;
    public static final sj Z7;
    public static final sj a7;
    public static final sj a8;
    public static final sj b7;
    public static final sj b8;
    public static final sj c7;
    public static final sj c8;
    public static final sj d7;
    public static final sj d8;
    public static final sj e7;
    public static final sj f7;
    public static final sj g7;
    public static final sj h7;
    public static final sj i7;
    public static final sj j7;
    public static final sj k7;
    public static final sj l7;
    public static final sj m7;
    public static final sj n7;
    public static final sj o7;
    public static final sj p7;
    public static final sj q7;
    public static final sj r7;
    public static final sj s7;
    public static final sj t7;
    public static final sj u7;
    public static final sj v7;
    public static final sj w7;
    public static final sj x7;
    public static final sj y7;
    public static final sj z7;

    static {
        TimeUnit timeUnit = TimeUnit.SECONDS;
        Q6 = com.applovin.impl.adview.t.c(timeUnit, 5L, "afi_ms");
        R6 = sj.a("mediation_endpoint", "https://ms.applovin.com/");
        S6 = sj.a("mediation_backup_endpoint", "https://ms.applvn.com/");
        T6 = com.applovin.impl.adview.t.c(timeUnit, 2L, "fetch_next_ad_retry_delay_ms");
        U6 = com.applovin.impl.adview.t.c(timeUnit, 30L, "fetch_next_ad_timeout_ms");
        V6 = com.applovin.impl.adview.t.c(timeUnit, 7L, "fetch_mediation_debugger_info_timeout_ms");
        Boolean bool = Boolean.TRUE;
        W6 = sj.a("auto_init_mediation_debugger", bool);
        X6 = sj.a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        Y6 = com.applovin.impl.adview.t.c(timeUnit, 30L, "max_signal_provider_latency_ms");
        Z6 = com.applovin.impl.adview.t.c(timeUnit, 10L, "default_adapter_timeout_ms");
        a7 = com.applovin.impl.adview.t.c(timeUnit, 30L, "ad_refresh_ms");
        b7 = com.applovin.impl.adview.t.c(timeUnit, 30L, "ad_load_failure_refresh_ms");
        c7 = sj.a("ad_load_failure_refresh_ignore_error_codes", "204");
        d7 = sj.a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        e7 = sj.a("refresh_ad_view_timer_responds_to_background", bool);
        f7 = sj.a("refresh_ad_view_timer_responds_to_store_kit", bool);
        Boolean bool2 = Boolean.FALSE;
        g7 = sj.a("refresh_ad_view_timer_responds_to_window_visibility_changed", bool2);
        h7 = sj.a("avrsponse", bool2);
        i7 = sj.a("allow_pause_auto_refresh_immediately", bool2);
        j7 = sj.a("ad_view_race_condition_fix_enabled", bool2);
        k7 = sj.a("fullscreen_display_delay_ms", 0L);
        l7 = sj.a("susaode", bool2);
        m7 = sj.a("ahdm", 500L);
        n7 = sj.a("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        o7 = sj.a("ad_view_refresh_precache_request_enabled", bool);
        p7 = sj.a("famttl_ms", 0L);
        q7 = sj.a("signal_expiration_ms", -1L);
        r7 = sj.a("signal_cache_level", Integer.valueOf(xj.b.AD_FORMAT.ordinal()));
        TimeUnit timeUnit2 = TimeUnit.HOURS;
        s7 = com.applovin.impl.adview.t.c(timeUnit2, 4L, "ad_expiration_ms");
        t7 = com.applovin.impl.adview.t.c(timeUnit2, 4L, "native_ad_expiration_ms");
        u7 = sj.a("rena", bool);
        v7 = sj.a("fullscreen_ad_displayed_timeout_ms", -1L);
        w7 = sj.a("freast_ms", -1L);
        x7 = sj.a("ad_hidden_timeout_ms", -1L);
        y7 = sj.a("schedule_ad_hidden_on_ad_dismiss", bool2);
        z7 = sj.a("schedule_ad_hidden_on_single_task_app_relaunch", bool2);
        A7 = com.applovin.impl.adview.t.c(timeUnit, 1L, "ad_hidden_on_ad_dismiss_callback_delay_ms");
        B7 = sj.a("proe", bool2);
        C7 = sj.a("mute_state", 2);
        D7 = sj.a("saf", "");
        E7 = sj.a("saui", "");
        F7 = sj.a("mra", -1);
        G7 = sj.a("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
        H7 = sj.a("svadfr", bool2);
        I7 = sj.a("mwalra", -1);
        J7 = com.applovin.impl.adview.t.c(timeUnit, 1L, "walrad_ms");
        K7 = sj.a("walriec", "");
        L7 = sj.a("fadiafase", bool);
        M7 = sj.a("fadwvcv", bool);
        N7 = sj.a("bfarud", bool2);
        O7 = sj.a("inacc", Boolean.valueOf(yp.b(Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        P7 = sj.a("pbataipaf", "");
        Q7 = com.applovin.impl.adview.t.c(timeUnit, 30L, "bwt_ms");
        R7 = com.applovin.impl.adview.t.c(timeUnit, 30L, "twt_ms");
        S7 = sj.a("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1L)));
        T7 = sj.a("faomq", bool2);
        U7 = sj.a("siflcfbt", bool2);
        V7 = sj.a("rahcnct_sec", -1);
        W7 = sj.a("uabta", bool2);
        X7 = sj.a("use_initialization_spec_during_init", bool2);
        Y7 = sj.a("use_promises_during_init", bool2);
        Z7 = sj.a("report_cimp_after_ierr", bool2);
        a8 = sj.a("fail_collection_for_empty_signal", bool2);
        b8 = sj.a("sdaomq", bool2);
        c8 = sj.a("fetch_mediated_ad_gzip", bool);
        d8 = sj.a("max_postback_gzip", bool);
    }
}
