package com.bytedance.sdk.openadsdk.GA;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.qO;
import com.bytedance.sdk.openadsdk.utils.GS;

/* loaded from: classes.dex */
public class GA extends com.bytedance.sdk.openadsdk.core.wN.DSW {
    public GA(Context context) {
        this(context, null);
    }

    private void YFl(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.wN.DSW dsw = new com.bytedance.sdk.openadsdk.core.wN.DSW(context);
        dsw.setId(com.bytedance.sdk.openadsdk.utils.GA.f10825qf);
        dsw.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        dsw.setBackgroundColor(0);
        dsw.setGravity(17);
        addView(dsw);
        View alY = new com.bytedance.sdk.openadsdk.core.wN.AlY(context);
        alY.setId(com.bytedance.sdk.openadsdk.utils.GA.HVP);
        alY.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        dsw.addView(alY);
        com.bytedance.sdk.openadsdk.core.wN.vc vcVar = new com.bytedance.sdk.openadsdk.core.wN.vc(context);
        vcVar.setId(com.bytedance.sdk.openadsdk.utils.GA.ep);
        int tN = GS.tN(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(tN, tN);
        layoutParams.addRule(13);
        vcVar.setLayoutParams(layoutParams);
        vcVar.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_video_loading_progress_bar"));
        dsw.addView(vcVar);
        com.bytedance.sdk.openadsdk.core.wN.wN wNVar = new com.bytedance.sdk.openadsdk.core.wN.wN(context);
        wNVar.setId(com.bytedance.sdk.openadsdk.utils.GA.EAq);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        wNVar.setLayoutParams(layoutParams2);
        wNVar.setGravity(1);
        wNVar.setOrientation(1);
        wNVar.setVisibility(8);
        dsw.addView(wNVar);
        com.bytedance.sdk.openadsdk.core.wN.AlY alY2 = new com.bytedance.sdk.openadsdk.core.wN.AlY(context);
        alY2.setId(com.bytedance.sdk.openadsdk.utils.GA.rog);
        alY2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        alY2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_refreshing_video_textpage"));
        alY2.setScaleType(ImageView.ScaleType.CENTER);
        wNVar.addView(alY2);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh.setId(com.bytedance.sdk.openadsdk.utils.GA.JT);
        qsh.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        qsh.setText(qO.YFl(context, "tt_video_retry_des_txt"));
        qsh.setTextColor(Color.parseColor("#999999"));
        wNVar.addView(qsh);
        com.bytedance.sdk.openadsdk.core.wN.AlY alY3 = new com.bytedance.sdk.openadsdk.core.wN.AlY(context);
        alY3.setId(com.bytedance.sdk.openadsdk.utils.GA.Lx);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        alY3.setLayoutParams(layoutParams3);
        alY3.setScaleType(ImageView.ScaleType.CENTER);
        alY3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_play_movebar_textpage"));
        alY3.setVisibility(8);
        addView(alY3);
        com.bytedance.sdk.openadsdk.core.wN.AlY alY4 = new com.bytedance.sdk.openadsdk.core.wN.AlY(context);
        alY4.setId(com.bytedance.sdk.openadsdk.utils.GA.dBO);
        int tN2 = GS.tN(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(tN2, tN2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int tN3 = GS.tN(context, 7.0f);
        layoutParams4.setMarginEnd(tN3);
        layoutParams4.rightMargin = tN3;
        layoutParams4.topMargin = tN3;
        alY4.setLayoutParams(layoutParams4);
        alY4.setBackground(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_detail_video_btn_bg"));
        alY4.setScaleType(ImageView.ScaleType.CENTER);
        alY4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_close_move_detail"));
        addView(alY4);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh2 = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh2.setId(com.bytedance.sdk.openadsdk.utils.GA.agS);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        qsh2.setLayoutParams(layoutParams5);
        qsh2.setBackground(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_video_black_desc_gradient"));
        qsh2.setEllipsize(TextUtils.TruncateAt.END);
        qsh2.setMaxLines(2);
        int tN4 = GS.tN(context, 15.0f);
        qsh2.setPadding(tN4, GS.tN(context, 14.0f), tN4, 0);
        qsh2.setSingleLine(false);
        qsh2.setTextColor(-1);
        qsh2.setTextSize(2, 17.0f);
        qsh2.setVisibility(8);
        addView(qsh2);
        com.bytedance.sdk.openadsdk.core.wN.DSW dsw2 = new com.bytedance.sdk.openadsdk.core.wN.DSW(context);
        dsw2.setId(com.bytedance.sdk.openadsdk.utils.GA.zl);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        dsw2.setLayoutParams(layoutParams6);
        dsw2.setBackground(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_video_black_desc_gradient"));
        dsw2.setGravity(16);
        dsw2.setVisibility(8);
        addView(dsw2);
        com.bytedance.sdk.openadsdk.core.wN.AlY alY5 = new com.bytedance.sdk.openadsdk.core.wN.AlY(context);
        int i10 = com.bytedance.sdk.openadsdk.utils.GA.f10816dc;
        alY5.setId(i10);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int tN5 = GS.tN(context, 12.0f);
        layoutParams7.leftMargin = tN5;
        layoutParams7.setMarginStart(tN5);
        alY5.setLayoutParams(layoutParams7);
        alY5.setScaleType(ImageView.ScaleType.CENTER);
        alY5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_leftbackbutton_titlebar_photo_preview"));
        dsw2.addView(alY5);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh3 = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh3.setId(com.bytedance.sdk.openadsdk.utils.GA.LL);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int tN6 = GS.tN(context, 16.0f);
        layoutParams8.leftMargin = tN6;
        layoutParams8.rightMargin = tN;
        layoutParams8.setMarginStart(tN6);
        layoutParams8.setMarginEnd(tN);
        layoutParams8.addRule(17, i10);
        int i11 = com.bytedance.sdk.openadsdk.utils.GA.toy;
        layoutParams8.addRule(0, i11);
        layoutParams8.addRule(1, i10);
        layoutParams8.addRule(16, i11);
        qsh3.setLayoutParams(layoutParams8);
        qsh3.setEllipsize(TextUtils.TruncateAt.END);
        qsh3.setGravity(16);
        qsh3.setMaxLines(1);
        qsh3.setSingleLine(true);
        qsh3.setTextColor(-1);
        qsh3.setTextSize(2, 17.0f);
        dsw2.addView(qsh3);
        com.bytedance.sdk.openadsdk.core.wN.wN wNVar2 = new com.bytedance.sdk.openadsdk.core.wN.wN(context);
        wNVar2.setId(i11);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int tN7 = GS.tN(context, 14.0f);
        layoutParams9.rightMargin = tN7;
        layoutParams9.setMarginEnd(tN7);
        wNVar2.setLayoutParams(layoutParams9);
        wNVar2.setGravity(16);
        wNVar2.setOrientation(1);
        dsw2.addView(wNVar2);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh4 = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh4.setId(com.bytedance.sdk.openadsdk.utils.GA.ww);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        qsh4.setLayoutParams(layoutParams10);
        qsh4.setGravity(16);
        qsh4.setMaxLines(1);
        qsh4.setSingleLine(true);
        qsh4.setTextColor(-1);
        qsh4.setTextSize(2, 12.0f);
        wNVar2.addView(qsh4);
        com.bytedance.sdk.openadsdk.core.wN.wN wNVar3 = new com.bytedance.sdk.openadsdk.core.wN.wN(context);
        wNVar3.setId(com.bytedance.sdk.openadsdk.utils.GA.JB);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, GS.tN(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        wNVar3.setLayoutParams(layoutParams11);
        wNVar3.setGravity(16);
        wNVar3.setOrientation(0);
        wNVar3.setVisibility(8);
        addView(wNVar3);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh5 = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh5.setId(com.bytedance.sdk.openadsdk.utils.GA.Uv);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = tN6;
        layoutParams12.rightMargin = tN5;
        layoutParams12.setMarginEnd(tN5);
        layoutParams12.setMarginStart(tN6);
        qsh5.setLayoutParams(layoutParams12);
        qsh5.setText(qO.YFl(context, "tt_00_00"));
        qsh5.setTextColor(-1);
        qsh5.setTextSize(2, 10.0f);
        wNVar3.addView(qsh5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(com.bytedance.sdk.openadsdk.utils.GA.JGG);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, GS.tN(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        wNVar3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh6 = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh6.setId(com.bytedance.sdk.openadsdk.utils.GA.f10823oa);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = tN5;
        layoutParams14.rightMargin = tN6;
        layoutParams14.setMarginEnd(tN6);
        layoutParams14.setMarginStart(tN5);
        qsh6.setLayoutParams(layoutParams14);
        qsh6.setText(qO.YFl(context, "tt_00_00"));
        qsh6.setTextColor(-1);
        qsh6.setTextSize(2, 10.0f);
        wNVar3.addView(qsh6);
        com.bytedance.sdk.openadsdk.core.wN.AlY alY6 = new com.bytedance.sdk.openadsdk.core.wN.AlY(context);
        alY6.setId(com.bytedance.sdk.openadsdk.utils.GA.f10820id);
        alY6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        alY6.setPadding(tN6, 0, tN6, 0);
        alY6.setScaleType(ImageView.ScaleType.CENTER);
        alY6.setVisibility(8);
        alY6.setImageDrawable(qO.tN(context, "tt_enlarge_video"));
        wNVar3.addView(alY6);
        View yoT = new YoT(context);
        yoT.setId(com.bytedance.sdk.openadsdk.utils.GA.pm);
        yoT.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(yoT);
        com.bytedance.sdk.openadsdk.core.wN.qsH qsh7 = new com.bytedance.sdk.openadsdk.core.wN.qsH(context);
        qsh7.setId(com.bytedance.sdk.openadsdk.utils.GA.TMt);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = tN5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        qsh7.setLayoutParams(layoutParams15);
        qsh7.setBackgroundColor(Color.parseColor("#00000000"));
        qsh7.setText("close");
        qsh7.setMinHeight(GS.tN(context, 44.0f));
        qsh7.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.qsH.YFl(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(qsh7);
    }

    public GA(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public GA(Context context, AttributeSet attributeSet, int i10) {
        super(context, attributeSet, i10);
        YFl(context);
    }
}
