package com.glority.android.app;

/* loaded from: classes.dex */
public final class BuildConfig {
    public static final String AB_HOST = "https://gw.coinidentifierai.com/abtesting";
    public static final String ADJUST_APP_TOKEN = "10d2c42pi5bk";
    public static final String ADJUST_NEED_SEND_SKU_PAYED = "null";
    public static final String ADJUST_OFFLINE_TRACKING = "true";
    public static final String ANALYSIS_HOST = "https://gw.coinidentifierai.com/tracking";
    public static final String ANALYSIS_PRODUCT_ID = "coin_61rl";
    public static final String ANALYSIS_SDK_VERSION = "1.5.1-realtimetest3";
    public static final String APPLICATION_ID = "com.coinidentifyer.ai";
    public static final String APP_NAME = "coin";
    public static final String BUILD_TYPE = "release";
    public static final String BUI_DEFAULT_MEMO = "27266";
    public static final String BUI_DEFAULT_MEMO_INDEX = "1";
    public static final String BUI_DEFAULT_MEMO_NOT_ENGLISH = "27266";
    public static final String BUI_DEFAULT_MEMO_NOT_ENGLISH_INDEX = "1";
    public static final String BUI_DEFAULT_MEMO_VIP_IN_HISTORY = "27267";
    public static final String BUI_DEFAULT_MEMO_VIP_IN_HISTORY_INDEX = "1";
    public static final String CMS_SEARCH_HOST = "https://cms-search-service.coinidentifierai.com";
    public static final String CONVERT_RETAIN_DEFAULT_MEMO = "27284";
    public static final String CONVERT_RETAIN_DEFAULT_MEMO_INDEX = "1";
    public static final boolean DEBUG = false;
    public static final Boolean DEBUG_MODE = false;
    public static final String DEEP_LINK_SCHEME = "coinidentifierai";
    public static final String DISABLE_LOG_EVENT_CHECKING = "false";
    public static final String ENV = "prod";
    public static final String EVENT_CONFIG_HOST = "https://gw.coinidentifierai.com/tracking-config";
    public static final String FAQ_JSON_LINK = "";
    public static final String GOOGLE_LOGIN_TOKEN = "";
    public static final String HOST = "https://app-service.coinidentifierai.com";
    public static final String INOUT = "global";
    public static final String PURCHASE_DETAIN_DEFAULT_MEMO = "27285";
    public static final String PURCHASE_DETAIN_DEFAULT_MEMO_INDEX = "1";
    public static final String PURCHASE_DETAIN_DEFAULT_MEMO_INDEX_NOT_ENGLISH = "1";
    public static final String PURCHASE_DETAIN_DEFAULT_MEMO_NOT_ENGLISH = "27285";
    public static final String QUESTIONNAIRE_LINK = "null";
    public static final String RETAIN_DEFAULT_MEMO = "null";
    public static final String TRACKING_KEY = "1bd2462077e211eb8cfbc3eedc210400";
    public static final int VERSION_CODE = 171;
    public static final String VERSION_NAME = "1.7.16";
    public static final String appName = "CoinSnap";
    public static final String contactEmail = "support@coinidentifierai.com";
    public static final String disableConversionPageInSplash = "false";
    public static final String enableGoogleLogin = "false";
    public static final String enableLogin = "true";
    public static final String enableMember = "true";
    public static final String hardcodeFirstConversionPage = "";
    public static final String isAppFromOfflineToOnline = "false";
}
