package com.bytedance.sdk.openadsdk.component.reward.view;

import android.R;
import android.content.Context;
import android.graphics.Color;
import android.text.TextUtils;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import com.bytedance.sdk.openadsdk.core.customview.PAGProgressBar;
import com.bytedance.sdk.openadsdk.core.customview.PAGTextView;
import com.bytedance.sdk.openadsdk.core.widget.TTRoundRectImageView;
import com.bytedance.sdk.openadsdk.utils.WNy;
import com.bytedance.sdk.openadsdk.utils.ku;

/* loaded from: classes.dex */
public class PAGPAGLoadingOneLayout extends PAGLoadingBaseLayout {
    public PAGPAGLoadingOneLayout(Context context) {
        super(context);
        LinearLayout linearLayout = new LinearLayout(context);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams.addRule(13);
        linearLayout.setLayoutParams(layoutParams);
        linearLayout.setGravity(17);
        linearLayout.setOrientation(1);
        TTRoundRectImageView tTRoundRectImageView = new TTRoundRectImageView(context);
        this.zp = tTRoundRectImageView;
        tTRoundRectImageView.setId(520093745);
        int lMd = WNy.lMd(context, 60.0f);
        this.zp.setLayoutParams(new RelativeLayout.LayoutParams(lMd, lMd));
        PAGTextView pAGTextView = new PAGTextView(context);
        this.lMd = pAGTextView;
        pAGTextView.setId(520093746);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, WNy.lMd(context, 28.0f));
        layoutParams2.topMargin = WNy.lMd(context, 24.0f);
        this.lMd.setLayoutParams(layoutParams2);
        this.lMd.setEllipsize(TextUtils.TruncateAt.END);
        this.lMd.setGravity(17);
        this.lMd.setMaxWidth(WNy.lMd(context, 150.0f));
        this.lMd.setSingleLine(true);
        this.lMd.setTextColor(Color.parseColor("#ffffff"));
        this.lMd.setTextSize(1, 20.0f);
        RelativeLayout relativeLayout = new RelativeLayout(context);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.topMargin = WNy.lMd(context, 32.0f);
        relativeLayout.setLayoutParams(layoutParams3);
        View view = new View(context);
        view.setId(520093747);
        view.setLayoutParams(new RelativeLayout.LayoutParams(WNy.lMd(context, 206.0f), WNy.lMd(context, 19.0f)));
        view.setBackground(ku.zp(context, "tt_ad_loading_rect"));
        PAGProgressBar pAGProgressBar = new PAGProgressBar(context, null, R.style.Widget.ProgressBar.Horizontal);
        this.KS = pAGProgressBar;
        pAGProgressBar.setId(520093748);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(WNy.lMd(context, 200.0f), WNy.lMd(context, 13.0f));
        layoutParams4.topMargin = WNy.lMd(context, 3.0f);
        layoutParams4.leftMargin = WNy.lMd(context, 3.0f);
        layoutParams4.setMarginStart(WNy.lMd(context, 3.0f));
        this.KS.setLayoutParams(layoutParams4);
        this.KS.setMax(100);
        this.KS.setProgress(1);
        this.KS.setProgressDrawable(ku.zp(context, "tt_full_reward_loading_progress_style"));
        relativeLayout.addView(view);
        relativeLayout.addView(this.KS);
        LinearLayout linearLayout2 = new LinearLayout(context);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -1);
        layoutParams5.topMargin = WNy.lMd(context, 13.0f);
        linearLayout2.setLayoutParams(layoutParams5);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(0);
        PAGTextView pAGTextView2 = new PAGTextView(context);
        pAGTextView2.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        pAGTextView2.setAlpha(0.5f);
        pAGTextView2.setTextColor(Color.parseColor("#FFFFFF"));
        pAGTextView2.setTextSize(1, 17.0f);
        pAGTextView2.setText("Loading");
        PAGTextView pAGTextView3 = new PAGTextView(context);
        this.jU = pAGTextView3;
        pAGTextView3.setId(520093749);
        this.jU.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        this.jU.setAlpha(0.5f);
        this.jU.setTextColor(Color.parseColor("#FFFFFF"));
        this.jU.setTextSize(1, 17.0f);
        PAGTextView pAGTextView4 = new PAGTextView(context);
        pAGTextView4.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        pAGTextView4.setAlpha(0.5f);
        pAGTextView4.setTextColor(Color.parseColor("#FFFFFF"));
        pAGTextView4.setTextSize(1, 17.0f);
        pAGTextView4.setText("%");
        linearLayout2.addView(pAGTextView2);
        linearLayout2.addView(this.jU);
        linearLayout2.addView(pAGTextView4);
        linearLayout.addView(this.zp);
        linearLayout.addView(this.lMd);
        linearLayout.addView(relativeLayout);
        linearLayout.addView(linearLayout2);
        zp(context);
        addView(linearLayout);
        addView(this.COT);
    }
}
