package com.bytedance.sdk.openadsdk.component.reward.view;

import android.content.Context;
import android.graphics.Color;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import com.bytedance.sdk.openadsdk.core.customview.PAGLinearLayout;
import com.bytedance.sdk.openadsdk.core.customview.PAGTextView;
import com.bytedance.sdk.openadsdk.utils.WNy;
import com.bytedance.sdk.openadsdk.utils.ku;

/* loaded from: classes.dex */
public class PAGPAGLoadingThreeLayout extends PAGLoadingBaseLayout {
    public PAGPAGLoadingThreeLayout(Context context) {
        super(context);
        LinearLayout linearLayout = new LinearLayout(context);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams.addRule(13);
        linearLayout.setLayoutParams(layoutParams);
        linearLayout.setOrientation(1);
        linearLayout.setGravity(17);
        PAGLinearLayout pAGLinearLayout = new PAGLinearLayout(context);
        this.HWF = pAGLinearLayout;
        pAGLinearLayout.setId(520093750);
        this.HWF.setLayoutParams(new LinearLayout.LayoutParams(-1, WNy.lMd(context, 60.0f)));
        this.HWF.setOrientation(0);
        this.HWF.setGravity(17);
        int lMd = WNy.lMd(context, 17.0f);
        int lMd2 = WNy.lMd(context, 35.0f);
        int lMd3 = WNy.lMd(context, -1.5f);
        View view = new View(context);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(lMd, lMd2);
        layoutParams2.rightMargin = lMd3;
        layoutParams2.setMarginEnd(lMd3);
        view.setLayoutParams(layoutParams2);
        view.setBackground(ku.zp(context, "tt_ad_loading_three_left"));
        View view2 = new View(context);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(lMd, lMd2);
        layoutParams3.rightMargin = lMd3;
        layoutParams3.setMarginEnd(lMd3);
        view2.setLayoutParams(layoutParams3);
        view2.setBackground(ku.zp(context, "tt_ad_loading_three_mid"));
        View view3 = new View(context);
        view3.setLayoutParams(new LinearLayout.LayoutParams(lMd, lMd2));
        view3.setBackground(ku.zp(context, "tt_ad_loading_three_mid"));
        View view4 = new View(context);
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(lMd, lMd2);
        layoutParams4.leftMargin = lMd3;
        layoutParams4.setMarginStart(lMd3);
        view4.setLayoutParams(layoutParams4);
        view4.setBackground(ku.zp(context, "tt_ad_loading_three_mid"));
        View view5 = new View(context);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(lMd, lMd2);
        layoutParams5.leftMargin = lMd3;
        layoutParams5.setMarginStart(lMd3);
        view5.setLayoutParams(layoutParams5);
        view5.setBackground(ku.zp(context, "tt_ad_loading_three_right"));
        this.HWF.addView(view);
        this.HWF.addView(view2);
        this.HWF.addView(view3);
        this.HWF.addView(view4);
        this.HWF.addView(view5);
        LinearLayout linearLayout2 = new LinearLayout(context);
        LinearLayout.LayoutParams layoutParams6 = new LinearLayout.LayoutParams(-1, -2);
        layoutParams6.topMargin = WNy.lMd(context, 10.0f);
        linearLayout2.setLayoutParams(layoutParams6);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(0);
        PAGTextView pAGTextView = new PAGTextView(context);
        pAGTextView.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        pAGTextView.setTextColor(Color.parseColor("#FFFFFF"));
        pAGTextView.setTextSize(1, 30.0f);
        pAGTextView.setText("Loading ");
        PAGTextView pAGTextView2 = new PAGTextView(context);
        this.jU = pAGTextView2;
        pAGTextView2.setId(520093749);
        this.jU.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        this.jU.setTextColor(Color.parseColor("#FFFFFF"));
        this.jU.setTextSize(1, 30.0f);
        PAGTextView pAGTextView3 = new PAGTextView(context);
        pAGTextView3.setLayoutParams(new RelativeLayout.LayoutParams(-2, -2));
        pAGTextView3.setTextColor(Color.parseColor("#FFFFFF"));
        pAGTextView3.setTextSize(1, 30.0f);
        pAGTextView3.setText("%");
        linearLayout2.addView(pAGTextView);
        linearLayout2.addView(this.jU);
        linearLayout2.addView(pAGTextView3);
        linearLayout.addView(this.HWF);
        linearLayout.addView(linearLayout2);
        zp(context);
        addView(linearLayout);
        addView(this.COT);
    }
}
